// Code generated by MockGen. DO NOT EDIT.
// Source: example.go

// Package mock_example is a generated GoMock package.
package mock_example

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockExample is a mock of Example interface
type MockExample struct {
	ctrl     *gomock.Controller
	recorder *MockExampleMockRecorder
}

// MockExampleMockRecorder is the mock recorder for MockExample
type MockExampleMockRecorder struct {
	mock *MockExample
}

// NewMockExample creates a new mock instance
func NewMockExample(ctrl *gomock.Controller) *MockExample {
	mock := &MockExample{ctrl: ctrl}
	mock.recorder = &MockExampleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockExample) EXPECT() *MockExampleMockRecorder {
	return m.recorder
}

// Method mocks base method
func (m *MockExample) Method(s string) int {
	ret := m.ctrl.Call(m, "Method", s)
	ret0, _ := ret[0].(int)
	return ret0
}

// Method indicates an expected call of Method
func (mr *MockExampleMockRecorder) Method(s interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Method", reflect.TypeOf((*MockExample)(nil).Method), s)
}
